spring.application.name=EcoomerceAplication
spring.profiles.active=dev

# H2 en memoria con modo PostgreSQL
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# CONFIGURACI�N JPA / MULTITENANT REFACTORIZADA
# ==========================================
# 1. Indicamos la estrategia multitenant para que Spring Boot active el motor
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# 2. CR�TICO: Cambiamos 'update' por 'none'. 
# Hibernate ya no intentar� crear tablas a ciegas en el arranque, evitando el crash.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Flyway deshabilitado en dev (�Ojo! Como pusimos ddl-auto=none, luego hablaremos de c�mo crear las tablas en H2)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/public
spring.flyway.schemas=public
spring.flyway.baseline-on-migrate=true



# ==========================================
# LOGS & SEGURIDAD (Tus propiedades intactas)
# ==========================================
logging.level.com.AplicatioEcommerce=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.hibernate.SQL=DEBUG

#JwUtiles
jwt.expiration-time=7200000
jwt.secretkey=843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3

#Cookies
app.cookie.secure=true
app.cookie.name=jwt
app.cookie.max-age=1800